### ISSUE TITLE
zepto

### ISSUE THREAD

**Issue by odd2008** [logoove/weui#120]
logove,您好
   我使用了您的组件，对微信的开发很有帮助。
    我看您的介绍里面对zepto进行了修改，目前我从github看到您的zepto是压缩之后的min文件，请问您修改之后未压缩前的zepto.js文件从哪儿获取？

**Comment by logoove** [comment]
我是把很多常用放在一个文件 实际上有很多插件

**Comment by a514117923** [comment]
请问下,可以用jq代替您的zepto吗?

**Comment by logoove** [comment]
不能 有些不支持jquery

**Comment by a514117923** [comment]
谢谢您的回复! 
请问下是少了Photo Browser这个功能吗

**Comment by logoove** [comment]
请使用微信jssdk实现 效果还比较好

**Comment by a514117923** [comment]
我没用过jssdk哈，不是专门用在微信上的页面，可以调用jssdk吗？

**Comment by logoove** [comment]
不能 jssdk必须在微信浏览器内部 否则就只能找相册插件
