### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by davecat** [logoove/weui#123]
滚蛋

**Comment by logoove** [comment]
不喜欢请滚蛋,老子没求你用,他妈的这就是weui增加了一些没有的组建,sb你厉害你做一个呀,尽说风凉话,本项目是个人用休息时间做的,你有啥权利在这里说三道四,再次申明,不喜欢你可以不用,你没资格否定别人脑动成果!!!

**Comment by logoove** [comment]
老子不欢迎你这种狗,来这里你素质高啥也没写的有,没本事写就闭嘴,你那是交流吗,诋毁一个产品,就像你吃奶骂娘,你凭啥建议别人,你算个什么东西,有多远滚多远
