### ISSUE TITLE
请教关于 weui_cell_hd在iPhone5s下的适配

### ISSUE THREAD

**Issue by cobola** [logoove/weui#13]
![image](https://cloud.githubusercontent.com/assets/4435875/17557081/626671fe-5f48-11e6-940e-7a70b2b14b8a.png)

如图所示

这个 宽度 363 是那儿得出来的呢？

没有找到相关的设置 导致 这个元素在5s下右边被截掉了

**Comment by logoove** [comment]
这个是 weui 官方的  最新版看看 修复没有
