### ISSUE TITLE
你好楼主

### ISSUE THREAD

**Issue by itluikuan** [logoove/weui#140]
那个你引入的weui 文件比较多，怎么才能只用官方css  然后你的功能才能用，不然的话，我引入官方的css文件然后再引入你的文件 weui2就会将以前用官方的weui功能不执行，没法用，然后你weui2和官方weui产生冗余代码，造成加载速度慢，请问怎么解决这个问题呢？

**Comment by logoove** [comment]
只需要引入 weuix.min.css一个文件即可 包含了所有css也不是很大加载一次就会缓存,里面还包含了图片字库
