### ISSUE TITLE
Swipe的高度如何调整？

### ISSUE THREAD

**Issue by smoothdvd** [logoove/weui#15]
Swipe的高度如何调整？

**Comment by logoove** [comment]
在img标签里  添加  width='640' height='200' 来设置宽高   或者修改css也可以

**Comment by smoothdvd** [comment]
@logoove 这样能自动根据屏幕宽度来调整高度吗？

**Comment by logoove** [comment]
高度是定值

**Comment by smoothdvd** [comment]
@logoove 太不灵活了, 改用swiper了

**Comment by logoove** [comment]
用什么你你的自由  至少我认为这个是最好用的 css是可以自己重写的  不会写这是你技术不够的问题
