### ISSUE TITLE
导航栏0下表是不是有问题

### ISSUE THREAD

**Issue by shanzhenghan** [logoove/weui#157]
//顶部导航栏，多个可滚动
        TagNav('#tagnav', {
            type: 'scrollToNext',
            curClassName: 'weui-state-active',
            index: 0,
            onToggle: function(index) {
                // $.alert(index);
            }
        });
        //顶部导航栏，固定个数，不可滚动
        $('#t1').tab({
            defaultIndex: 0,
            activeClass: 'tab-green',
            onToggle: function(index) {
                // $.alert(index);
            }
        });
        //顶部导航栏，固定个数，不可滚动(带圆角)
        $('#t4').tab({
            defaultIndex: 0,
            activeClass: "bg-green",
            onToggle: function(index) {
                // $.alert(index);
            }
        });
        //底部Tab导航
        $('.weui-tab').tab({
            defaultIndex: 0,
            activeClass: 'weui-bar__item_on',
            onToggle: function(index) {
                $.toast(index);
            }
        })

默认是选择了0，但是点击再切回0 的时候 $.toast(index);  index不为0吗 toast不出来？

还有一会侧滑删除的关闭功能好像也有点儿问题：
  $('.close-swipeout').click(function() {
                $(this).parents('.weui-cell').swipeout('close');
            })

缩不回去

**Comment by logoove** [comment]
第一个问题描述不清;滑动功能是演示滑动的  删除只是演示如果在滑动中实现功能  关闭只是菜单名字 你想自己实现关闭也行 但是可以参考微信中 是不存在关闭滑动的

**Comment by shanzhenghan** [comment]
> 第一个问题描述不清;滑动功能是演示滑动的 删除只是演示如果在滑动中实现功能 关闭只是菜单名字 你想自己实现关闭也行 但是可以参考微信中 是不存在关闭滑动的

**Comment by shanzhenghan** [comment]
> 第一个问题描述不清;滑动功能是演示滑动的 删除只是演示如果在滑动中实现功能 关闭只是菜单名字 你想自己实现关闭也行 但是可以参考微信中 是不存在关闭滑动的

嗯嗯 确实不存在关闭的选项，第一个问题是这样的  就比如Tab标签页有两个标签：首页和我的  默认选择的是首页的Tab 没问题  当我点击“我的”选项时 会执行$.toast(index); 弹出“1”下标来  也没问题  但是 当我再点击首页的Tab的时候，为啥没有弹出“0”来 好像是显示的别的提示或者是没提示
