### ISSUE TITLE
popup无法正常使用

### ISSUE THREAD

**Issue by crisis123** [logoove/weui#163]
http://weui.shanliwawa.top/   

weui+5 --> B表单 --> popup/通知出现以下问题：
（1）显示全屏和显示底部Popup都不正常，点击后闪退；
（2）显示全屏和显示底部Popup按钮在连续点击5次左右后就不可再次点击，只能刷新页面在点击才有反应。

请问以上该如何解决？谢谢。

**Comment by logoove** [comment]
不知道你什么机型 测试在iphone xr 12.1.4版本没有你说的问题

**Comment by crisis123** [comment]
我的iPhone8p也没有问题、我在chrome、firefox上也没有问题，但是我同事的小米8、iPhone6、iPhone6s都有问题。
我直接用我同事的小米8在微信里打开http://weui.shanliwawa.top/这个页面，点进popup，第一次点击闪退，然后就再也无法点击，只能后退再进才能再点。

**Comment by crisis123** [comment]
iphone的版本都是最新的12.1.4，小米8是MIUI10.2，百度说是基于安卓9做得开发

**Comment by logoove** [comment]
没有你说的那些手机 具体可以用vconsole工具查看在手机上报什么js错误
