### ISSUE TITLE
你好，那下拉更新的框不能用在微信开发者工具里面报错，因为被动监听事件不能用preventDeafualt()阻止

### ISSUE THREAD

**Issue by buyingorangefather** [logoove/weui#165]
zepto.min.js:1 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
具体以上解释。我也是刚刚查资料发现的这个问题，如果我的解释讲错什么的话，请直接指明。

**Comment by buyingorangefather** [comment]
我是用
![image](https://user-images.githubusercontent.com/41496272/52908547-fce5d900-32b2-11e9-83b5-202599f8fb01.png)

**Comment by TomLiu-GitHub** [comment]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See  这问题折腾了我几个小时,不知道哪里有冲突

**Comment by TomLiu-GitHub** [comment]
为什么没解决,就closed了

**Comment by TomLiu-GitHub** [comment]
![image](https://user-images.githubusercontent.com/32833966/60500609-3876c200-9ced-11e9-8ffb-1e5e21705ba7.png)
不仅是微信浏览器啊,chrome也一样
