### ISSUE TITLE
点击 tab 时 当前tab的 onToggle 回调多次

### ISSUE THREAD

**Issue by o624366705** [logoove/weui#167]
此处代码来自自带demo
` $('#t1').tab({
            defaultIndex: 0,
            activeClass: 'tab-green',
            onToggle: function (index) {
                console.log('index'+index);
            }
        });`
点击一次tab可以看到console 显示多次index，在我点击tab拉取数据的时候执行了多次
谢谢

**Comment by o624366705** [comment]
明白了，tap与click的事件穿透，有没有办法解决

**Comment by maplezero** [comment]
后来怎么解决的？我也遇到这个问题。

**Comment by logoove** [comment]
已修复 替换weui.min文件即可
