### ISSUE TITLE
weui实现多层级的展开和收起

### ISSUE THREAD

**Issue by xiaobu1994** [logoove/weui#174]
![https://weui.io](http://ws2.sinaimg.cn/large/0062Ue2Wgy1g37t8oqn64j30dc0m8jxu.jpg)

我想实现这样的效果，请问有demo示例么。实现点击展开之后一层一层的展开，收起的时候也是一样。

**Comment by logoove** [comment]
没有 你直接扒这个用就行了

**Comment by xiaobu1994** [comment]
大佬，你指的是你weui+的首页的展示和收起吗
