### ISSUE TITLE
引入css和js 运行 提示：$.toast is not a function

### ISSUE THREAD

**Issue by XiaoYong666** [logoove/weui#176]
$.toast is not a function 这个是什么错误？还需要引入别的什么吗？

**Comment by logoove** [comment]
<link rel="stylesheet" href="../css/weuix.min.css"/>

<script src="../js/zepto.min.js"></script>
<script src="../js/zepto.weui.js"></script>
一般就这三个 个别需要单独引入的看演示例子

**Comment by XiaoYong666** [comment]
好的， 已搞定，谢谢
