### ISSUE TITLE
访问不了

### ISSUE THREAD

**Issue by connertang** [logoove/weui#178]
http://weui.shanliwawa.top

**Comment by logoove** [comment]
昨天换服务器 中途断了一段时间 已经好了

**Comment by logoove** [comment]
https://weui.shanliwawa.top/

**Comment by connertang** [comment]
好的 谢谢




------------------ 原始邮件 ------------------
发件人: "Yoby"<notifications@github.com>; 
发送时间: 2019年6月18日(星期二) 下午4:58
收件人: "logoove/weui"<weui@noreply.github.com>; 
抄送: "Connor Temple"<751682337@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [logoove/weui] 访问不了 (#178)




昨天换服务器 中途断了一段时间 已经好了
