### ISSUE TITLE
亲爱的楼主

### ISSUE THREAD

**Issue by TomLiu-GitHub** [logoove/weui#179]
我觉得这个很多东西并没有考虑手机用户,虽然电脑上用鼠标和滚轮测试ok,但实际用手机的时候发现完全没法用啊.
比如表单输入后键盘区域空白.
美化单选复选文本框文本域 手机不容易点中等.

**Comment by logoove** [comment]
手机机型太多 每个系统也有很多版本 不能一一测试 只在自己 iphone XR 和 小米9测试过; 汇报bug 一定要说明手机型号和系统版本

**Comment by TomLiu-GitHub** [comment]
好的,我在自己 iphone XR 和 小米9,还有同事的华为mate 20pro等等很多种机型测试过.一样的效果.
不论什么手机,请试试美化单选复选文本框文本域 手机不容易点中,一点要很精确的去点那个圆点才能选中.什么手机可以的话请告诉型号,我买个和你一样的手机.

**Comment by logoove** [comment]
是要点到控件上 文字上不起作用 因为我一查没有用过这个美化组件,等我今明两天更新下

**Comment by logoove** [comment]
已修复,点击文字就能选中

**Comment by TomLiu-GitHub** [comment]
辛苦了,感谢.另外还有,没加footer的时候,ios文本框输入后
![image](https://user-images.githubusercontent.com/32833966/60939276-a59be000-a309-11e9-9763-2758fe66421f.png)
![image](https://user-images.githubusercontent.com/32833966/60939282-ab91c100-a309-11e9-88be-0167ed420bad.png)

**Comment by logoove** [comment]
你说的这个问题是ios微信浏览器bug,如果不在微信浏览器中是没有任何问题的,如果不想要footer可以加一个空的 实际上就是给最后一个元素用fixed定位,

**Comment by logoove** [comment]
表单输入后键盘区域空白.这是微信浏览器没有回弹导致的,而且也只是在ios微信中出现,(我只测试了自己有的手机) 跟上面遮挡控件类似,目前没有可行修复办法,搜索到的也都是不完美修复,会导致新bug
