### ISSUE TITLE
ios文本框输入 键盘区域的空白不回弹

### ISSUE THREAD

**Issue by TomLiu-GitHub** [logoove/weui#180]
> 微信浏览器ios文本框输入的问题

https://weui.shanliwawa.top/demo/form2.html
# 输入时

<img src="https://user-images.githubusercontent.com/32833966/61256171-48d37600-a79e-11e9-8f5c-b4c376f1c8e8.png"  height="330" >

# 输入完成后

<img src="https://user-images.githubusercontent.com/32833966/61256181-525cde00-a79e-11e9-8441-35ec89e8dd52.png"  height="330" >

# 键盘区域的白色下不去

_Originally posted by @TomLiu-GitHub in https://github.com/logoove/weui/issues/179#issuecomment-510717588_

**Comment by logoove** [comment]
这是ios微信浏览器bug 你不使用任何框架也会有这个问题 目前没有完美解决方法

**Comment by TomLiu-GitHub** [comment]
```
$("input,select,textarea").blur(function(){
setTimeout(() => {
const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0;
window.scrollTo(0, Math.max(scrollHeight - 1, 0));
}, 100);
})
```

暂时解决办法，应该是IOS微信6.7.4和IOS12问题

**Comment by logoove** [comment]
这样可以 我更新上去了 除了微信ios以外都不会有这个问题
