### ISSUE TITLE
tabbar的demo无法切换页面

### ISSUE THREAD

**Issue by yezi34880** [logoove/weui#181]
tabbar的demo无法切换页面，只有按钮响应，页面无法切换

**Comment by logoove** [comment]
切换页面在href里面填写具体链接,切换div做ajax即可

**Comment by yezi34880** [comment]
> 切换页面在href里面填写具体链接,切换div做ajax即可

明白了，这样也行，我以为是像一般那种<tab,tabcontent>对应，有内联的超链接 #id 这种的呢

**Comment by logoove** [comment]
tabcontent 填写内容切换也是可以的 你更新一下 我在例子上加了div切换
