### ISSUE TITLE
WeUI+是否考虑将px转换为rem？

### ISSUE THREAD

**Issue by bbtflash** [logoove/weui#187]
现在rem应该更适合移动端开发，作者是否可以px转换为rem?

**Comment by logoove** [comment]
主要以em为主的,weui官方就是此单位,单位之间都是可以相互转换的,默认情况下1rem=16px 1em=16px
rem好处是不受父元素影响 ;weui默认根元素大小是16px

**Comment by logoove** [comment]
主要以em为主的,weui官方就是此单位,单位之间都是可以相互转换的,默认情况下1rem=16px 1em=16px
rem好处是不受父元素影响 ;weui默认根元素大小是16px
