### ISSUE TITLE
图片预览和缩放的问题

### ISSUE THREAD

**Issue by xuewlw** [logoove/weui#188]
点击图片列表当中的一张图片 可以在全屏看到这张图片 并可以对这张图片实现手势缩放 这两个功能使用哪个组件实现 或者说代码怎么写好 能提供个思路吗 看到gallery是先隐藏后显示 好像不是解决这个问题的组件  谢谢

**Comment by logoove** [comment]
如果是公众号中直接 在图片img标签 添加  weixin类即可,就能调用微信自带相册 微信自带相册就有看大图和缩放功能,非公众号看看这个插件https://github.com/webjyh/MPreview.mobile

**Comment by xuewlw** [comment]
确实是在公众号中开发 但你所说的weixin类是指js-sdk 还是其它 能给个网址吗 另如果是指js-sdk是不是previewImage这个方法 谢谢

**Comment by logoove** [comment]
已经封装这个调用的 https://weui.shanliwawa.top/demo/js17.html

**Comment by xuewlw** [comment]
好的 您所说的weixin类其实就是指js-sdk是吧
