### ISSUE TITLE
weui3.1发布啦

### ISSUE THREAD

**Issue by logoove** [logoove/weui#19]
经过多天测试终于通过了ios android测试 如果个别机型有bug 请在此提交问题 包括机型  系统版本 截图等信息

**Comment by ImHUan** [comment]
很好奇这个 和官方发布的区别都有哪些呢？https://github.com/weui/weui

**Comment by logoove** [comment]
增强版 数倍于官方组件 官方的太弱了 看看演示不就清楚了

**Comment by ImHUan** [comment]
演示是看了，确实是比官方多了一些样式，但还是不够直观。最好有个对比表格就好了哈。也不是想麻烦你，只是隐约觉得你的东西很好，作为一个锦鲤都不知道怎么和工程师同学们推荐呢

**Comment by yanlu19860713** [comment]
左滑动滑出之后必须要滑动别的列表才能把滑出的给滑回去吗？ 不能做到点击别的地方滑回去么 ？ 类似这种的  http://light7.cn/demos/list/swipeout/

**Comment by yanlu19860713** [comment]
新增导航横向滚动在哪啊 ？ 没找到啊 ！

**Comment by logoove** [comment]
组件-tabbar里面

**Comment by 7PLonG** [comment]
建议把weui样式同步到1.0+版本

**Comment by logoove** [comment]
@7PLonG 建议你看一下weui0.44与1.0区别再来说这句话 官方都说的很明白了 不兼容 0.44已是终极版

**Comment by 7PLonG** [comment]
[https://github.com/weui/weui/wiki/%E5%9C%A81.0.0%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%B1%82%E9%9D%A2%E4%B8%8A%E5%81%9A%E4%BA%86%E5%93%AA%E4%BA%9B%E6%94%B9%E5%8F%98](url)
已看，上条挂两天我自己删，多有冒犯，您别生气。

**Comment by yanlu19860713** [comment]
上拉加载下拉刷新 和 图片懒加载不能共用啊
