### ISSUE TITLE
在 Pop弹出层 如果有input等表单元素出现点击错位问题

### ISSUE THREAD

**Issue by ccliqi** [logoove/weui#190]
出现场景：IOS端，在弹出层点击input时调起键盘页面会被顶上去document.body.scrollOffset大于0，收起键盘时scrollOffset不变，造成焦点错位。

jq处理： 
 $('input').on('blur', function (event) {
 　　if (!(event.relatedTarget && event.relatedTarget.tagName)) document.body.scrollTop = 0;
 });
看作者能不能集成在项目里解决。

**Comment by logoove** [comment]
这个问题早有人提出来解决了 在form2.html演示有
 $(function(){
 $("input,select,textarea").blur(function(){
setTimeout(() => {
const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0;
window.scrollTo(0, Math.max(scrollHeight - 1, 0));
}, 100);
})
        });
