### ISSUE TITLE
picker在tabbar中内联显示不正常等

### ISSUE THREAD

**Issue by zdy1658** [logoove/weui#191]
问题描述：

1. 我想在tabbar的一个标签页中，内联显示picker控件，但是页面中显示不正常。
2. picker的高度是否可调整。

代码：
`

	<div class="weui-tab" style="height:auto;">
		
		<div class="weui-tab__panel">
			<div id="c0" class="weui-tab__content">中国</div>
			<div id="c1" class="weui-tab__content">
				
				<div class="weui-cell">
					<div class="weui-cell__hd"><label for="input-size" class="weui-label">请输入</label></div>
					<div class="weui-cell__bd">
						<input class="weui-input" id="input-select" type="text" value="">
					</div>
				</div>
				<div id="picker-container"></div>
			</div>
			<div id="c2" class="weui-tab__content">
				<div class="weui-cells__title">带说明、跳转的列表项</div>
			    <div class="weui-cells">
			        <a class="weui-cell weui-cell_access" href="javascript:;">
			            <div class="weui-cell__bd">
			                <p>百度</p>
			            </div>
			            <div class="weui-cell__ft">修改</div>
			        </a>
			        <a class="weui-cell weui-cell_access" href="javascript:;">
			            <div class="weui-cell__bd">
			                <p>谷歌</p>
			            </div>
			            <div class="weui-cell__ft">修改</div>
			        </a>
			
			    </div>
			</div>
		</div>
		
		<div class="weui-tabbar tab-bottom">
			<a href="javascript:;" class="weui-tabbar__item ">
				<i class="icon icon-101 f27 weui-tabbar__icon" ></i>
				<p class="weui-tabbar__label">设置</p>
			</a>
			<a href="javascript:;" class="weui-tabbar__item">
				<i class="icon icon-4 f27 weui-tabbar__icon"></i>
				<p class="weui-tabbar__label">查询</p>
			</a>
			<a href="javascript:;" class="weui-tabbar__item">
				<span style="display: inline-block;position: relative;">
					<i class="icon icon-28 f27 weui-tabbar__icon"></i>
					<span id="shopping-num" class="weui-badge" style="position: absolute;top: -2px;right: -13px;">0</span>
				</span>
				<p class="weui-tabbar__label">购物车</p>
			</a>
		</div>
	</div>`
现象：
![微信图片_20190920140544](https://user-images.githubusercontent.com/35281586/65304914-6e249c00-dbb4-11e9-9765-bdf879a7fe75.jpg)

**Comment by logoove** [comment]
高度是13rem  距离底部0 你可以自己修改
