### ISSUE TITLE
少了微信最重要的聊天界面和公众号界面

### ISSUE THREAD

**Issue by shijunti19** [logoove/weui#20]
少了微信最重要的聊天界面和公众号界面
![1](https://cloud.githubusercontent.com/assets/5392211/19460591/9b8eb624-950f-11e6-9832-cf347410567f.jpg)
![2](https://cloud.githubusercontent.com/assets/5392211/19460594/9fe6d3be-950f-11e6-8f56-8a5620c34d56.jpg)

**Comment by logoove** [comment]
做开发是不会用到这样界面的 这属于app界面  看来你不做公众号开发

**Comment by shijunti19** [comment]
是这样的，公众号开发，一般都点进去跳到自己的网站，但是公众号本身他缺少会员和会员之间的交流，如果有这种界面的话，他更符合微信，某个会员分享了图片，可以及时更新到这种界面上，实时互动吧，我做后端的，前端没找到这种类似的！

**Comment by logoove** [comment]
因为几乎没人用 所以就没有
