### ISSUE TITLE
请问仿今日头条导航怎么滚动

### ISSUE THREAD

**Issue by laiyangFly** [logoove/weui#200]
JS有方法可以让导航滚动到特定的位置吗？看了看源码
`var tNav = TagNav('#tagnav',{
    type: 'scrollToNext',
    curClassName: 'weui-state-active',
    index:0
});`
`setTimeout(function(){
   tNav.switchTo(7)
})`
不行，请指教

**Comment by logoove** [comment]
要加载js插件 看演示
