### ISSUE TITLE
tab底部菜单，weui-tab__content中放tab头部导航，点击头部导航，底部导航跟着切换了。

### ISSUE THREAD

**Issue by pkkgu** [logoove/weui#218]
如题

**Comment by pkkgu** [comment]
`        const $tabbarItems = this.**children().children**('.weui-tabbar__item, .weui-navbar__item');
        const $tabBdItems = this.**children().children**('.weui-tab__content');
`
`        this.on('click', '.weui-tabbar__item, .weui-navbar__item', function (e) {
            const index = $(this).index();
            self.toggle(index);
            **return false;**
        });
`

**Comment by logoove** [comment]
已有最新演示 可以同一页面
