### ISSUE TITLE
图片验证码

### ISSUE THREAD

**Issue by ZeroIndra** [logoove/weui#219]
你好,我想问下图片验证码怎么获取值和文本框中输入的值做对比

**Comment by logoove** [comment]
使用编程语言生成图片验证码同时生成session，验证码就存在session中然后把表单中值通过ajax传入到后台和session中验证，成功或失败都返回提示，不管php  java 原理都一样

**Comment by ZeroIndra** [comment]
我用的是示例中的function getcode(){
            $("#code").attr("src","../php/code.php?random="+Math.random());
        };
从session中也能取到吗

**Comment by logoove** [comment]
当然后端程序会吧验证码存在session中 这跟短信验证一个道理，不过短信验证一般把验证码存到数据库或redis缓存中

**Comment by ZeroIndra** [comment]
好的,谢谢
