### ISSUE TITLE
关于TagNav

### ISSUE THREAD

**Issue by whatlife** [logoove/weui#22]
同一个页面里调用TagNav两次，则无法正常定位到当前Nav。
如有A B两个Nav，都调用了TagNav，当我点击A里的Tag时，会影响到B的Nav也增加样式。AB Nav分别在不同的DOM

` 

        function navScroll() {
            TagNav('#dataCenterNav',{
                type: 'scrollToFirst',
                curClassName: 'current'
            });
        }
        function mySpaceToolBoxScroll() {
        TagNav('#SpaceToolBoxScroll',{
                type: 'scrollToFirst',
                curClassName: 'current'
            });
        }
`

**Comment by logoove** [comment]
同一页面不建议使用两个
