### ISSUE TITLE
select组件初始化数据之后，重新设置新的数据无法

### ISSUE THREAD

**Issue by XuRuiXi** [logoove/weui#221]
![image](https://user-images.githubusercontent.com/37138056/80168594-d5587200-8615-11ea-978d-cadcf3b0b93b.png)
对.applicantCertType设置data的下拉列表之后，再设置通过异步接口回来的data1，无法更新下拉列表。还是以前data的数据
![image](https://user-images.githubusercontent.com/37138056/80168704-236d7580-8616-11ea-897f-f12573e59fec.png)

**Comment by Darling-Pan** [comment]
我也是    重新   接口返回data   下拉框 还是以前的数据。

**Comment by pkkgu** [comment]
$("input").select("update", { items: ["法官", "猎人"] })
初始化后要通过这种方法动态更新配置
@XuRuiXi @Darling-Pan
