### ISSUE TITLE
tabbar show、hide、fadeIn、fadeOut

### ISSUE THREAD

**Issue by pkkgu** [logoove/weui#222]
tabbar 组件压缩和未压缩用的方法不一样
zepto.weui.js show、hide
$defaultTabBdItem.**show**().**siblings**().hide();
zepot.weui.min.js fadeIn、fadeOut
h.**fadeIn**().siblings().**fadeOut**();

**Comment by logoove** [comment]
已不提供压缩版了,需要的自己压缩,可能我工具有问题
