### ISSUE TITLE
weui-tab在快速切换时页面会空白

### ISSUE THREAD

**Issue by wenjian337** [logoove/weui#225]
`<div class="weui-tab" id="media-live-tab">
        <div class="weui-navbar">
              <div class="weui-navbar__item tab-blue" >简介</div>
            <div class="weui-navbar__item">往期回顾</div>   
      </div>
        <div class="weui-tab__panel"><br>
               <div class="weui-tab__content" ></div>
            <div class="weui-tab__content" ></div>
      </div>
    </div>
`

快速来回切换会导致content不能显示

**Comment by pkkgu** [comment]
#222 有可能是同一个问题，我不是很确定。可以用非压缩版试试。

**Comment by logoove** [comment]
以后不提供压缩版了,估计压缩工具问题
