### ISSUE TITLE
navbar/今日头条导航  的 tab  选项可以点击切换，但是  tab 切换页的样式内容是什么

### ISSUE THREAD

**Issue by xingx001** [logoove/weui#231]
navbar/今日头条导航  的 tab  选项可以点击切换，但是  tab 切换的样式内容是什么给个例子
 比如中国 美国 小日本  tab 页面下面内容 是什么

**Comment by logoove** [comment]
可以是具体页面html或者通过ajax来获取内容添加到当前页面

**Comment by xingx001** [comment]
> 可以是具体页面html或者通过ajax来获取内容添加到当前页面

这个也要在一个div下 随 tab的切换  这个div的切换控制样式是什么  比如你底部导航的切换是 <div id="c0" class="weui-tab__content">内容1</div>
