### ISSUE TITLE
作者可否把better-scroll组件整合进来，滚动效果还是非常非常常用的，现在的版本中没有

### ISSUE THREAD

**Issue by startjava** [logoove/weui#233]
作者可否把better-scroll组件整合进来，滚动效果还是非常非常常用的，现在的版本中没有

**Comment by logoove** [comment]
里面有 注意找找http://weui.shanliwawa.top/demo/js6.html 轮播

**Comment by startjava** [comment]
不是轮播，大哥，是better-scroll，，，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yoby"<notifications@github.com&gt;; 
发送时间: 2020年11月28日(星期六) 凌晨5:46
收件人: "logoove/weui"<weui@noreply.github.com&gt;; 
抄送: "一直以来"<279377921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [logoove/weui] 作者可否把better-scroll组件整合进来，滚动效果还是非常非常常用的，现在的版本中没有 (#233)





 
里面有 注意找找http://weui.shanliwawa.top/demo/js6.html 轮播

**Comment by logoove** [comment]
看了下开源的https://github.com/ustbhuangyi/better-scroll 里面演示效果 基本上本项目都包括在内了 没必要重复引入

**Comment by startjava** [comment]
tabbar内容多时，自动出现垂直滚动条？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yoby"<notifications@github.com&gt;; 
发送时间: 2020年11月30日(星期一) 下午3:43
收件人: "logoove/weui"<weui@noreply.github.com&gt;; 
抄送: "一直以来"<279377921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [logoove/weui] 作者可否把better-scroll组件整合进来，滚动效果还是非常非常常用的，现在的版本中没有 (#233)





 
看了下开源的https://github.com/ustbhuangyi/better-scroll 里面演示效果 基本上本项目都包括在内了 没必要重复引入
