### ISSUE TITLE
picker的onClose方法

### ISSUE THREAD

**Issue by qinst64** [logoove/weui#234]
picker的`onClose` 只接受一个参数, 代码
相关代码
 __zepto.weui.js__: ` if (p.params.onClose) p.params.onClose(p);`

但是[示例](https://weui.shanliwawa.top/demo/form4.html)中:
``` javascript
    $("#mobile").picker({
        title: "请选择您的电脑",
        cols: [
            {
                textAlign: 'center',
                values: ['苹果','三星','联想']
            }
        ],
        onChange: function(p, v, dv) {
            console.log(p, v, dv);
        },
        onClose: function(p, v, d) {
            console.log("close");
        }
    });
```
为了统一可以一起修改成3个参数的形式。

**Comment by logoove** [comment]
这是打印参数 你想打印几个都可以，下面那个是关闭

**Comment by qinst64** [comment]
我的意思是, `zepto.weui.js`中onClose只传了一个参数过去。示例中`console.log(p, v, dv)` 后面2个参数打印出来自然是undefined, 不合理. 

其他组件都是正常传了3个参数, 这个`zepto.weui.js`需要fix一下, onClose传3个参数(和其他组件的onClose一样)
