### ISSUE TITLE
访今日头条导航如何监听我点击了哪一个

### ISSUE THREAD

**Issue by jidilang** [logoove/weui#239]
第一个 TagNav('#tagnav',{
                type: 'scrollToNext',
                curClassName: 'weui-state-active',
                index:2,
            });
如何监听我点击了哪一个？

**Comment by logoove** [comment]
这个用js写一个就行了`   let arr= $("#tagnav li")
          for(let i=0;i<arr.length;i++)
        {
           arr[i].index=i;
             arr[i].onclick=function(){
                console.log(this.index);
             }
        }`
