### ISSUE TITLE
时间日期选择器 滚动选择日期的时候出现下面错误

### ISSUE THREAD

**Issue by wangtao1994** [logoove/weui#242]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

**Comment by logoove** [comment]
并没有发现你说的错误

**Comment by wangtao1994** [comment]
gg

**Comment by wangtao1994** [comment]
一滚动就出现红色报错。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "logoove/weui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 中午12:48
***@***.***&gt;;
抄送:&nbsp;"Love  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [logoove/weui] 时间日期选择器 滚动选择日期的时候出现下面错误 (#242)





 
并没有发现你说的错误

**Comment by wangtao1994** [comment]
![image](https://user-images.githubusercontent.com/23544856/122868976-2e2cb300-d35e-11eb-8be8-76c58a647493.png)

**Comment by logoove** [comment]
![](http://mini.srsw580.com/1.png) 不知道什么原因 我的没问题

**Comment by wangtao1994** [comment]
![image](https://user-images.githubusercontent.com/23544856/122875529-f7a76600-d366-11eb-9ff5-bb6edbd26bc0.png)
你得也有一个错误

**Comment by logoove** [comment]
那不是 js错误 那是站点ico图标不存在

**Comment by logoove** [comment]
不过我用的是EDGE浏览器,微信开发者工具估计也是调用的这个,一般我不在开发者工具测试,直接是浏览器上开手机模式

**Comment by wangtao1994** [comment]
你直接浏览器打开&nbsp;&nbsp;


地址：&nbsp;https://weui.shanliwawa.top/weui/demo/form4.html





最后来个 qq或者微信联系方式


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "logoove/weui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 下午2:41
***@***.***&gt;;
抄送:&nbsp;"Love  ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [logoove/weui] 时间日期选择器 滚动选择日期的时候出现下面错误 (#242)





 
那不是 js错误 那是站点ico图标不存在
