### ISSUE TITLE
域名访问不了了

### ISSUE THREAD

**Issue by shuaidawang** [logoove/weui#252]
[weui.shanliwawa.top/](https://weui.shanliwawa.top/) 访问不了了

**Comment by logoove** [comment]
没钱 倒了

**Comment by cshitian** [comment]
http://155.248.199.78:8885/weui/index.html      试试这个， 我搞了个小服务器来运行这项目。

**Comment by scottfly189** [comment]
兄弟，我赞助了15元，收到吗？请你抽一包双喜

**Comment by logoove** [comment]
谢谢你收到了，过段时间不忙了重新买个云服务器

**Comment by logoove** [comment]
> [weui.shanliwawa.top/](https://weui.shanliwawa.top/) 访问不了了

2024-2-24买了阿里云99一年恢复了
