### ISSUE TITLE
能不能升级到weui2.6?

### ISSUE THREAD

**Issue by scottfly189** [logoove/weui#257]
现在weui升级到2.6版了，支持自适应light/dark模式，界面感觉漂亮很多，有计划升级到weui2.6吗？谢谢！

**Comment by logoove** [comment]
> 现在weui升级到2.6版了，支持自适应light/dark模式，界面感觉漂亮很多，有计划升级到weui2.6吗？谢谢！

工作量太大了要适配各种组件，暗黑模式更多用在app，网站/公众号用的并不多
