### ISSUE TITLE
表单提交项中有picker项,如果首次提交失败,就一直显示为红色

### ISSUE THREAD

**Issue by WangShayne** [logoove/weui#27]
![image](https://cloud.githubusercontent.com/assets/17644818/20918667/326af334-bbd3-11e6-9ee4-1a4602ee6ea3.png)
其中一项为picker的选择项,如果首次校验失败,后面就算选择了值也不能返回正常的状态

测试机型:Nexus 6
版本:6.0
wx版本:6.3.31

**Comment by logoove** [comment]
不清楚 你说的具体问题  对于验证 建议只使用 tips提示 ,而不要去修饰 红色叹号 和文本框 以及文字 , 你说的问题很可能 是你js写的有问题

**Comment by WangShayne** [comment]
@logoove sorry,我表述的不够清楚.我重新描述一下

如图所示,报警原因这个地方是picker做的.当我不选择任何值的时候提交表单,会有文字和感叹号以及Tip提示未填写,当我选择了值之后,文字和感叹号的效果并没有消失

**Comment by logoove** [comment]
地址 发我 我测试看
我在使用中并未遇到你说的 像地址选择 日期时间  这些都是picker做的 并未遇到你说的

**Comment by WangShayne** [comment]
测试地址   [http://shayne.tunnel.qydev.com/wx/submitAlarm](url)

现在已经解决了
我把zepto中的validate中"foucus"事件改成"click"就ok了,但不知道会不会有bug...感谢!

**Comment by logoove** [comment]
一般使用 click 或 tap事件

**Comment by WangShayne** [comment]
ok,谢谢!
