### ISSUE TITLE
打分功能有bug

### ISSUE THREAD

**Issue by winsom** [logoove/weui#28]
点击后面几颗星的时候，比如第四颗星，期望应该是前面4颗星都点亮，实际上只是第一颗和第四颗亮了

**Comment by logoove** [comment]
打分这个并非bug  具体应用时候需要你写 js代码去控制  这里只是提供了样式 我花时间  写了一个  你现在可以去看演示  已经完全支持了  当然你可以根据自己情况写js  例子仅供参考
