### ISSUE TITLE
使用过程中遇到bug或不解,建议,都可以在此提问

### ISSUE THREAD

**Issue by logoove** [logoove/weui#30]
bug请附上截图,说明问题,以及演示页面,包括出现bug的手机机型,以便快速找到错误

**Comment by WangShayne** [comment]
![image](https://cloud.githubusercontent.com/assets/17644818/20995703/bc6aaff0-bd33-11e6-9307-553b9927048e.png)

请问一下,模板引擎输出input的value值时,会截断空格,怎么解决呢 ?

**Comment by logoove** [comment]
我测试 并不存在你说的这种问题 参看<http://weixin.yoby123.cn/weui/c/cell6.html>  查看网页源代码就能看到 模板 使用方法 请检查你的代码

**Comment by WangShayne** [comment]
@logoove 谢谢,找到原因了,我的value没加 " "

**Comment by WangShayne** [comment]
请问dataTimePicker如何默认时间呢?

**Comment by qinqin123** [comment]
请问没有源码吗？那如果我想改颜色这些怎么办呢？

**Comment by logoove** [comment]
包含七种颜色  平常应该够用了 除了  红绿蓝黑白 增加了 橙色 紫色
