### ISSUE TITLE
picker引用你的js，无法识别piker方法

### ISSUE THREAD

**Issue by liaoyuheng00** [logoove/weui#32]
picker引用你的js，无法识别piker方法

**Comment by logoove** [comment]
参考我的演示 我要胡乱引入 注意顺序

**Comment by liaoyuheng00** [comment]
你好，有API吗？
看下谢谢了




------------------ 原始邮件 ------------------
发件人: "Yoby";<notifications@github.com>;
发送时间: 2016年12月14日(星期三) 中午1:01
收件人: "logoove/weui"<weui@noreply.github.com>; 
抄送: "就是自己哈"<978464953@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [logoove/weui] picker引用你的js，无法识别piker方法 (#32)




参考我的演示 我要胡乱引入 注意顺序

**Comment by WangShayne** [comment]
搭车请教!
$(this).val('')清空以后,再次点击需要滑动选择后才会更新值到输入框中,如何能像首次点击一样直接赋值呢?

**Comment by logoove** [comment]
focus事件

**Comment by WangShayne** [comment]
我还是没能解决这个问题,恕我愚钝...
![1](https://cloud.githubusercontent.com/assets/17644818/21216246/a24fe06a-c2e0-11e6-937b-8b891ac409ea.gif)

**Comment by logoove** [comment]
给出页面地址

**Comment by WangShayne** [comment]
http://shayne.tunnel.qydev.com/wx/myAlarms

**Comment by logoove** [comment]
设置初始值

**Comment by logoove** [comment]
另一种办法 是改用datetime 和select 控件 这个是表单自带的

**Comment by WangShayne** [comment]
hi,我找到解决办法了,把input的data-picker也清空就好了
