### ISSUE TITLE
字体的大小是不是不可以随屏幕自适应？

### ISSUE THREAD

**Issue by enlyck** [logoove/weui#36]

**Comment by logoove** [comment]
字体大小是随手机浏览器默认大小 具体就是微信浏览器默认大小   一般屏幕大看起来就大 详细参考官方weui

**Comment by enlyck** [comment]
@logoove 我看了一下css样式，里面的字体有的不是默认值，对于px为单位的字体也会随着屏幕大小而改变么？ 不太明白，请不吝赐教
