### ISSUE TITLE
.weui_tab_nav{display:box;display:-webkit-box;display:-webkit-flex;display:display:flex}

### ISSUE THREAD

**Issue by shijunti19** [logoove/weui#38]
.weui_tab_nav{display:box;display:-webkit-box;display:-webkit-flex;display:display:flex}这个你写错了吧display:display:flex

**Comment by shijunti19** [comment]
background: linear-gradient(to top, #fff 0%, #efefef 100%);这个也写错了吧，少了to

**Comment by shijunti19** [comment]
.weui_tab_nav {
    display: box;
    display: -webkit-box;
    display: -webkit-flex;
    display: flex
}
display: box;和display: flex是不是有冲突

**Comment by logoove** [comment]
box是老机型  flex新机型支持  浏览器会优先选择 并不会冲突

**Comment by shijunti19** [comment]
@logoove 哦，我弄到vue2里居然提示我。不熟悉这个！
