### ISSUE TITLE
有计划升级到 WeUI 1.x 吗？

### ISSUE THREAD

**Issue by southwolf** [logoove/weui#40]
谢谢您优秀的工作！目前这个项目还是基于 WeUI 0.4x, 不知道有没有计划升级到 WeUI 1.x 呢？

**Comment by shijunti19** [comment]
是啊，我也在用，升级吗？

**Comment by logoove** [comment]
永远不升1.x但是1.x的ui会移植到0.4  原因是个人不习惯 他们命名BEM  虽然这种属于css推荐命令  但是使用要长期习惯  其次移植工作量太大  官方UI组建太少了
