### ISSUE TITLE
【bug】发现完全不兼容weui1.1所有效果

### ISSUE THREAD

**Issue by web525** [logoove/weui#46]
【bug】发现完全不兼容weui1.1所有效果
WeUI v1.1.1 (https://github.com/weui/weui)

**Comment by logoove** [comment]
不知你说的哪个没有  常用的都移植过来了  或者我的已有更好替代品

**Comment by web525** [comment]
你把微信官方V1.1.1的demo（WeUI v1.1.1 (https://github.com/weui/weui)）项目里面的weui.css文件，替换成weui+4.0的weuix.min.css，样式全部错乱

**Comment by web525** [comment]
哦，明白了，您的意思是weui+完全包含官方V1.1的所有效果，但是不兼容weui1.1

**Comment by logoove** [comment]
1.1使用BEM规范写的  肯定是不一样的
