### ISSUE TITLE
weui2.css有错。。。

### ISSUE THREAD

**Issue by jifengdehao** [logoove/weui#50]

**Comment by logoove** [comment]
具体说出错误

**Comment by jifengdehao** [comment]
![5 h4f4ojak76pqmiiyd_9s6](https://cloud.githubusercontent.com/assets/17547658/24182905/de38bbae-0eff-11e7-8a56-f4b3dd02b5b9.png)
![k33xtebzf 1aa x70f ond0](https://cloud.githubusercontent.com/assets/17547658/24182906/de4df80c-0eff-11e7-8351-077824ca94c1.png)
![Uploading Q`(XC0P0S0BV(NU2(I_0G1G.png…]()
![Uploading U_5JBNPB87LSC6GBZI(~IED.png…]()

**Comment by jifengdehao** [comment]
![Uploading 5]H4F4OJAK76PQMIIYD_9S6.png…]()
![Uploading K33XTEBZF)1AA)X70F$OND0.png…]()
![Uploading Q`(XC0P0S0BV(NU2(I_0G1G.png…]()
![Uploading   U_5JBNPB87LSC6GBZI(~IED.png…]()

**Comment by jifengdehao** [comment]
![5 h4f4ojak76pqmiiyd_9s6](https://cloud.githubusercontent.com/assets/17547658/24183034/7871466e-0f00-11e7-88ec-8b34a0cfab6b.png)

**Comment by jifengdehao** [comment]
![k33xtebzf 1aa x70f ond0](https://cloud.githubusercontent.com/assets/17547658/24183040/82d58af2-0f00-11e7-9214-e10abc4e593f.png)

**Comment by jifengdehao** [comment]
![q xc0p0s0bv nu2 i_0g1g](https://cloud.githubusercontent.com/assets/17547658/24183041/89a46402-0f00-11e7-8b2b-6187cf268563.png)

**Comment by jifengdehao** [comment]
![u_5jbnpb87lsc6gbzi ied](https://cloud.githubusercontent.com/assets/17547658/24183064/b3caea1c-0f00-11e7-8ca8-d81f2a6deffc.png)
