### ISSUE TITLE
搜索框那里的onInput函数没用啊。没法触发input事件

### ISSUE THREAD

**Issue by qinqin123** [logoove/weui#56]

**Comment by logoove** [comment]
没看懂你说的啥

**Comment by qinqin123** [comment]
就是在表单-搜索里面的第一个搜索框。在文件中是form8.html。第22行oninput中写东西：alert（‘11’）。但是在搜索框中输入关键字的时候不会弹出来。我试了其他的比如onblur这些都可以。这里的用法难道有什么要求吗？谢谢了
