### ISSUE TITLE
关于DateTimePicker默认值的问题

### ISSUE THREAD

**Issue by zxz19** [logoove/weui#57]
因为需求原因（需要打开datetimepicker时时见是当前时间往后一个小时），我在页面加载后给input设置了默认值，然后调用dateTimePicker方法，但是发现一个问题，在展开的时间选择器中，只有当小时，分钟等全部都被拖动重新选择了之后才会触发选择器选中方法，不然input里面的值是不会改变的。如果此时点击“完成”,再次点开选择器时，选择器默认时间会变成1950。。。这个最小的初始值了。

关键代码类似如下：
$("#appointment").val("2017-03-28 14:30");
$("#appointment").datetimePicker({ title: "选择日期时间" });

请问如过需要设置一个默认选中时间该如何正确处理？

**Comment by logoove** [comment]
默认值 直接写到 input里面即可

**Comment by zxz19** [comment]
这样$("#appointment").val("2017-03-28 14:30");赋值与直接写到input的value有差别？

**Comment by logoove** [comment]
可以把js写到 $(function(){})中

**Comment by zxz19** [comment]
我写的应该是和写在那里面一样的。我是单独在外面写了一个function，然后在$(function(){})对其调用的
