### ISSUE TITLE
关于popup.也就是表单-popup,select。打开是文件form5.html。这个打开全屏的用法有什么要求吗。

### ISSUE THREAD

**Issue by qinqin123** [logoove/weui#58]
我这边设置好了以后。在安卓上打开没有问题。但是在iPhone7中点击没有反应，也就是打不开全屏弹窗。这个打开的弹窗的标签必须是a标签吗？还是有其他的要求。我写的是用div来打开的。就是<div class="open-popup"  data-target="#window"></div>这样子写的。就出现了上述问题。iPhone其他的版本没有测过。

**Comment by logoove** [comment]
我用ip7  10.3 没任何问题 onclick就可以 不一定a标记
