### ISSUE TITLE
关于上拉下拉的自动加载的问题。

### ISSUE THREAD

**Issue by qinqin123** [logoove/weui#59]
不好意思，又来打扰你了，只是最近在用的过程中真的遇到了很多问题，望不吝赐教。按照js中的代码，应该是只要autoLoad设置为true就会自动加载的是吗？但是我觉得很奇怪，之前设置为false的时候他还是会自动加载。但是现在是true它又不自动加载了。只能下拉或者上拉加载。这个的用法也有什么要求吗？

**Comment by logoove** [comment]
调试看 有没有js错误 这个就是上拉加载下拉刷新

**Comment by qinqin123** [comment]
请问一下那个scorllrea是指整个滚动的窗口吗？我找的的问题是当我得 内容超过了屏幕的大小就不会自动加载了。请问这个是怎么回事

**Comment by logoove** [comment]
https://github.com/ximan/dropload 是这个插件 有啥给作者提  我只是整合过来
