### ISSUE TITLE
关于pop select的bug

### ISSUE THREAD

**Issue by tohkinzhu** [logoove/weui#60]
http://weixin.yoby123.cn/weui/c/form5.html
1.选择弹出复选，先选中2个，再把他们勾掉，然后再点开发现他们任然是选中状态。
 2.在有pop弹出一个层的时候，页面同时有弹出单选、弹出多选。会出现单选，多选的文字在pop的层之上。

**Comment by logoove** [comment]
1没发现你说的   2pop又不是最顶层

**Comment by tohkinzhu** [comment]
1.你按照我的操作来：
1.先点弹出复选，然后选择2个，然后点击完成。
2.再次点开弹出复选，再把那原先选中的那2个勾掉，点击完成。
3.再次点开弹出复选。（发现被勾掉的那2个又选中了）

2.还是这个页面，在弹出复选的HTML下面加个原生的Select，然后点击弹出层试一下。
比如：
<div class="weui_cell weui_cell_select weui_select_after">
                <div class="weui_cell_hd">
                    <label for="" class="weui_label">国家/地区</label>
                </div>
                <div class="weui_cell_bd weui_cell_primary">
                    <select class="weui_select" name="select2">
                        <option value="1">中国</option>
                        <option value="2">美国</option>
                        <option value="3">英国</option>
                    </select>
                </div>
</div>

**Comment by tohkinzhu** [comment]
HTML被过滤了。。。就是加个这个页面的http://weixin.yoby123.cn/weui/c/form2.html
国家/地区 这个select在下面
