### ISSUE TITLE
关于上拉和下拉的问题

### ISSUE THREAD

**Issue by qinqin123** [logoove/weui#61]
经过我逐条数据对比。终于找到了原因。是因为当我的body里面的内容超过了设备屏幕，也就是window的高度的时候。自动加载就会失效。我试着将scrollArea设置成ducment的时候可以自动加载了，但是却有报错：Uncaught TypeError:1.$scrollArea.on is not a function()           updown.js:6

**Comment by qinqin123** [comment]
说错了，不得自动加载。要报错

**Comment by qinqin123** [comment]
这是一个bug，请看看

**Comment by logoove** [comment]
https://github.com/ximan/dropload  bug提交给这个  是这个人开发的
