### ISSUE TITLE
TagNav使用问题

### ISSUE THREAD

**Issue by ybzy920** [logoove/weui#65]
TagNav的参数有哪些，点击后只能向右滚动，不能向左滚动，只能用手向左滑动才能看到前面的；

TagNav点击后，对应的内容是怎么显示的，例子上也没有，只有tab的内容切换；

**Comment by logoove** [comment]
支持左右滑动
放a标记

**Comment by ybzy920** [comment]
我说的是，TagNav点击后，下方应有对应的内容切换，比如TagNav中<li><a href="javascript:;">军事</a></li><li><a href="javascript:;">社会</a></li>，点击“军事”或者“社会”，下方对应有相应的内容切换，是怎么来放html代码的？

**Comment by logoove** [comment]
使用连接不同页面即可

**Comment by ybzy920** [comment]
那不是直接跳转页面了？
