### ISSUE TITLE
zepto和weui.js整合了，能不能提供一个未压缩版本呢

### ISSUE THREAD

**Issue by xcondor** [logoove/weui#67]
zepto和weui.js整合了，能不能提供一个未压缩版本呢

**Comment by xcondor** [comment]
picker整合后有触发的问题。如果不是input触发，就会有时而无法弹出的问题，value值也无法回填。

**Comment by logoove** [comment]
没有未压缩  picker只支持input

**Comment by xcondor** [comment]
picker 的回调onConfirm 也没了？我看回调只有onchange了。
