### ISSUE TITLE
下拉加载更多，返回上一页存在bug

### ISSUE THREAD

**Issue by web-zwy** [logoove/weui#70]
下拉加载更多，返回上一页window.history.go(-1);或者点击网页后退键不能一次性回到上一页

**Comment by logoove** [comment]
ajax载入的 要想返回正常需要重写地址url 自己解决吧  window.history.replaceState和window.history.pushState的应用

**Comment by web-zwy** [comment]
有没有什么demo推荐下呀

**Comment by logoove** [comment]
自己写 一般返回上页  直接写上一页地址  而不是js的返回上一页  ajax载入是没有地址改变的

**Comment by web-zwy** [comment]
window.history.pushState(null, document.title, window.location.href); 代码中这句话不用，现在已经可以了
