### ISSUE TITLE
tabbar 不能正确显示

### ISSUE THREAD

**Issue by captaintong** [logoove/weui#71]
你好。我引用了style目录下的 v0.4.3 的weui.css 以及weui2.css 的样式，tabbar 没有正确显示，如下图：
![issue](https://cloud.githubusercontent.com/assets/13618335/25471099/13d27c04-2b58-11e7-8e7f-27fd61a35303.jpeg)

代码如下：

![image](https://cloud.githubusercontent.com/assets/13618335/25471180/77faf10c-2b58-11e7-9ffd-1c72924c2afd.png)

请问是什么原因导致？

**Comment by logoove** [comment]
缺js

**Comment by logoove** [comment]
看例子 都是有js控制的
