### ISSUE TITLE
多图压缩上传好像有个bug，404了。接口返回undefined

### ISSUE THREAD

**Issue by xcondor** [logoove/weui#75]
如demo，只要压缩的好像都报错了。并且只能上传一次。http://weixin.yoby123.cn/weui/c/js10.html

**Comment by logoove** [comment]
没发现你说的 我在多个项目中都有使用

**Comment by xcondor** [comment]
![image](https://cloud.githubusercontent.com/assets/3349113/25729097/cf8c4fca-3165-11e7-9968-014815460af7.png)
返回的图片地址404.

**Comment by logoove** [comment]
我服务器没给写入权限 自己放本地测试吧
