### ISSUE TITLE
如何限制多选的个数

### ISSUE THREAD

**Issue by hwhbug** [logoove/weui#77]

**Comment by logoove** [comment]
js计算数量

**Comment by hwhbug** [comment]
function upDownOperation(element) {
            var count = 0;
            var _input = element.parent().find('input');
            for (var i = 0; i < _input.length; i++) {
                if (_input[i].checked == true) {
                    //选中的操作
                    count++;
                }
            }            
            if (count > parseInt(@Model.numberrule)) {
                element.find('input').checked = false;
            }
        }

**Comment by hwhbug** [comment]
function upDownOperation(element) {
            var count = 0;
            var _input = element.parent().find('input');
            for (var i = 0; i < _input.length; i++) {
                if (_input[i].checked == true) {
                    //选中的操作
                    count++;
                }
            }            
            if (count > 2) {
                element.find('input').checked = false;//这句话没法撤销input的选中
            }
        }

**Comment by hwhbug** [comment]
prop("checked",false)已解决
