### ISSUE TITLE
select设置默认值后在ios下打开不了在android下没有问题

### ISSUE THREAD

**Issue by ghostsf** [logoove/weui#82]
RT
select设置默认值后在ios下打开不了在android下没有问题

**Comment by logoove** [comment]
给出具体页面地址 我用过很多次select 没你说的

**Comment by ghostsf** [comment]
发现问题所在了，就是被ios自带的完成的对话框挡住了，包括你公众号上的demo也是。但是我这个直接被挡住了。demo地址：http://www.xqcpjy.com/cp/register
select框里的内容被ios的完成框挡住了。

**Comment by ghostsf** [comment]
这个似乎不大好解决。实在不行就改用picker了，picker没问题。
查到一些处理方案大致如此： document.activeElement.blur();$("input").blur(); 但是我这边试了并没有起作用,ios的完成弹出框还是存在。

**Comment by ghostsf** [comment]
解决了 给input添加click事件 在click事件里执行document.activeElement.blur();$(this).blur(); 即可。
这样就避免了ios自带的那个完成的弹出框。
