### ISSUE TITLE
关于ｓｅｌｅｃｔ的问题

### ISSUE THREAD

**Issue by 13145209391** [logoove/weui#85]
请问在ｓｅｌｅｃｔ里的选项ｏｐｔｉｏｎ怎么请求数据放在ｉｔｅｍｓ数组中？或者有没有其他更好的办法

**Comment by logoove** [comment]
用编程语言 生成

**Comment by 13145209391** [comment]
可以详细说下吗

<script>
    var page_type = 'select';
    $(function(){
	    var to = $("#d1").select({
	        title: "选择一个选项",
	        autoClose:true,
	        
	        items: ['选项1','选项2']
	    });
	    console.log(to)
	});    
      </script>
items这个数组怎么取出来啊？
