### ISSUE TITLE
图片懒加载问题

### ISSUE THREAD

**Issue by ablikim915** [logoove/weui#89]
![qq 20170601141814](https://cloud.githubusercontent.com/assets/15664144/26666937/30cb5158-46d5-11e7-83bc-e0baaa838d01.png)
打开新页面的时候用过懒加载的图片不会自动显示，滑动页面或者触摸页面的时候才能显示，怎么解决这个问题？

**Comment by ablikim915** [comment]
没有人遇到过这种情况吗

**Comment by logoove** [comment]
没有你说的那种问题 看我演示 或者你给个连接
