### ISSUE TITLE
加一个步进器进去吧。。

### ISSUE THREAD

**Issue by canyue1980** [logoove/weui#91]
加一个步进器进去吧，这个组件还是比较常用的。

**Comment by logoove** [comment]
什么东东

**Comment by fuzhaohao** [comment]
@logoove 
应该是跟这个问题一样#88 
这里有讲到2个步进器的概念 http://www.uisdc.com/stepper-and-switch

**Comment by logoove** [comment]
你说的加减操作 里面有 你没仔细看

**Comment by logoove** [comment]
表单第六个 加减操作

**Comment by canyue1980** [comment]
呃呃。。不是这个，是叫 步聚条。。说错了。。 跟那个时间轴差不多，不过是横向的。

**Comment by logoove** [comment]
自己写吧 这个几乎用不到

**Comment by canyue1980** [comment]
嗯，用了另一个库，可以完美解决
https://github.com/aliceui/step
