### ISSUE TITLE
$.toast方法，没有删除mask层

### ISSUE THREAD

**Issue by nszbf** [logoove/weui#97]

**Comment by kdndkarv** [comment]
遇到同样的问题。没有自动删除，会不断增加。
<div class="weui_mask_transparent" style="display: none;"></div>

zepto.min.js 第1205行左右

.....
a(".weui_mask_transparent").hide(), a(".weui_toast_visible").removeClass("weui_toast_visible").transitionEnd(function () {
            a(this).remove()
        })
需要在此处增加  ,$(".weui_mask_transparent").remove()  ，好自动删除mask层。

--- 还是thanks，提供这个项目。

**Comment by canyue1980** [comment]
是没有删除。看着不爽。对于你说的1205行。。。是格式化后的吗？

**Comment by kdndkarv** [comment]
zepto.min.js 没有原文件，格式化后1205行左右。
